[Interface]
PrivateKey = cccccccccccccccccccccccccccccccccccccccccc=
Address = 172.16.0.1/24
Table = 100

[Peer]
PublicKey = DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD=
Name = spoke-one
AllowedIPs = 172.16.10.0/24, 172.16.11.0/24
Endpoint = 192.0.2.99:51820
