[package]
name = "pair_eval"
version = "0.1.0"
edition = "2021"

[dependencies]
avsc_json = { path = "../avsc_json" }
reader_default = { path = "../reader_default" }
branch_set = { path = "../branch_set" }
logical_check = { path = "../logical_check" }
fqdn_alias = { path = "../fqdn_alias" }
canonical_fp = { path = "../canonical_fp" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

