[Interface]
PrivateKey = HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH=
Address = 100.64.0.1/24
Table = 407

[Peer]
PublicKey = IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII=
Name = rand-alpha
AllowedIPs = 100.64.10.0/24, 100.64.11.0/24
Endpoint = 198.18.50.9:51820

[Peer]
PublicKey = JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ=
Name = rand-beta
AllowedIPs = 100.64.20.0/24

[Peer]
PublicKey = KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK=
Name = rand-disabled
AllowedIPs = 100.64.99.0/24
