[package]
name = "nmeapipeline"
version.workspace = true
edition.workspace = true

[[bin]]
name = "nmeapipeline"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
