[package]
name = "term-lsp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "term-lsp"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
docdiag = { path = "../docdiag" }
docmodel = { path = "../docmodel" }
docsync = { path = "../docsync" }
docexport = { path = "../docexport" }
serde = { workspace = true }
serde_json = { workspace = true }
