[Interface]
PrivateKey = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=
Address = 10.0.0.1/24
Table = 200

[Peer]
PublicKey = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
Name = peer-alpha
AllowedIPs = 10.10.0.0/24, 10.10.1.0/32
Endpoint = 203.0.113.99:51820

[Peer]
PublicKey = BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=
Name = peer-beta
AllowedIPs = 10.20.0.0/24

[Peer]
PublicKey = GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG=
Name = peer-gamma
AllowedIPs = 10.99.0.0/24
