[package]
name = "search-export"
version.workspace = true
edition.workspace = true

[dependencies]
ts-types = { workspace = true }
ts-filter = { workspace = true }
ts-ranker = { workspace = true }
ts-facet = { workspace = true }
ts-fuzzy = { workspace = true }
ts-tokenize = { workspace = true }
query-planner = { workspace = true }
