[Interface]
PrivateKey = LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL=
Address = 10.200.0.1/24
Table = 509

[Peer]
PublicKey = MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=
Name = trap-left
AllowedIPs = 10.200.64.0/24, 10.200.65.0/32

[Peer]
PublicKey = NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN=
Name = trap-right
AllowedIPs = 10.200.64.128/25
