[package]
name = "typesense-search-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "typesense-search-cli"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
serde_json = { workspace = true }
ingest-stage = { workspace = true }
search-export = { workspace = true }
ts-types = { workspace = true }
