[package]
name = "craft-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "crafter"
path = "src/main.rs"

[dependencies]
craft-core = { path = "../craft-core" }
inventory-db = { path = "../inventory-db" }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
